name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Building the client
        if: ${{ steps.cache-wheels.outputs.cache-hit != 'true' }}
        run: |
          ls -l server
          cp -rf ../server/protos/ .
          cd client && python -m pip wheel -w ./wheelhouse .
        env:
          CIBW_BUILD: "cp39-manylinux_*" # force python 3.9 and manylinux for this build
          CIBW_ARCHS: x86_64 # ignore i686/x86 (32bit) for now, as well as arm and stuff

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
