name: Test client

on:
  push:
    branches: [master]
    paths: ["docs/**", "examples/**", "bastionai/examples/**", ".github/**"]
  pull_request:
    branches: [master]
    paths: ["docs/**", "examples/**", "bastionai/examples/**", ".github/**"]

jobs:
  python_ci:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - clientImage: bastionlab
            os: ubuntu-latest
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      ########## SETUP ##########
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      ########### GET CLIENT ##########
      - name: Wait for build of server to finish
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: "build-client (ubuntu-latest)"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download artifact
        id: download-artifact-client
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          name: ${{ matrix.clientImage }}
          workflow_conclusion: success
          path: /tmp
      - name: Install client wheel
        run: |
          python -m pip install ./tmp/${{ matrix.clientImage }}.whl

      ########### GET SERVER ##########
      - name: Wait for build of server to finish
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: "build-server (bastionlab)"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          name: ${{ matrix.serverImage }}
          workflow_conclusion: success
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ matrix.serverImage }}.tar
          docker image ls -a
      - name: Launch server
        run: |
          docker kill -f app > /dev/null 2>&1 || true
          docker run --rm -d -e BASTIONLAB_DISABLE_TELEMETRY=1 -p 50056:50056  --name app ${{ matrix.serverImage }}:latest
      ########## TESTING NOTEBOOK ##########
      - name: Testing the notebooks
        run: |
          find . -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute {} \;
